[project]
name = "businesslicensenavigator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent>=0.1.3",
    "fastapi>=0.116.1",
    "langchain>=0.3.27",
    "openai>=1.97.1",
    "pydantic>=2.11.7",
    "requests>=2.31.0",
    "streamlit>=1.47.1",
    "uvicorn>=0.35.0",
]
